### ISSUE TITLE
Filtrar accesos de robots en la consulta a Solr

### ISSUE THREAD

**Issue by toniprieto** [lareferencia/dspace-stats-collector#22]
DSpace puede llegar a clasificar accesos que registra en Solr como realizados por robots en base a una lista de expresiones regulares que aplica sobre el user-agent, el dns o ips concretas.

Por defecto estos accesos detectados se añaden a Solr con un atributo isBot a true, aunque se puede modificar para que no se registren si se pone a false la clave de configuración `usage-statistics.logBots` de `usage-statistics.cfg`. También se puede borrar periódicamente lanzando:

`dspace stats-util -f`

Para reducir el tiempo que pasa el cliente procesando estos accesos puede ser buena idea filtrarlos en la consulta de solr añadiendo `+isBot:false` en el parámetro `fq` de la consulta.

**Comment by lareferencia** [comment]
@toniprieto hecho! por favor haz un test y cerramos este issue

**Comment by toniprieto** [comment]
Probado. Todo ok!
