### ISSUE TITLE
Se borra el archivo de log al ejecutar el collector

### ISSUE THREAD

**Issue by arieljlira** [lareferencia/dspace-stats-collector#3]
Cada vez que se ejecuta la herramienta se pisa el archivo de log ./var/logs/dspace-stats-collector.log
 Estimo que el problema está en  https://github.com/lareferencia/dspace-stats-collector/blob/ca59486a4ac3d9759d68ce13ee81aaee49d3e34e/dspace_stats_collector/collector.py#L87-L90
que abre el archivo de log en modo write 'w' en lugar de modo append 'a'.

**Comment by lmatas** [comment]
Gracias @arieljlira  acabo de corregirlo, de hecho el default es 'a'
Sentite libre de hacer pull requests si lo consideras.
